language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install: pip install -e .; pip install -r dev-requirements.txt; pip install coveralls
cache: pip
script:
  - nosetests --cover-erase --cover-package=pythonwhois --with-coverage

after_success:
  - coveralls